grafana:
  fullnameOverride: grafana
  adminUser: "${grafana_admin_username}"
  adminPassword: "${grafana_admin_password}"
  service:
    type: ClusterIP
  persistence:
    enabled: false

prometheus:
  prometheusSpec:
    retention: 7d
    scrapeInterval: 30s
    evaluationInterval: 30s
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 2Gi

alertmanager:
  enabled: false

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false
