output "aws_region" {
  description = "AWS region used by the project."
  value       = var.aws_region
}

output "terraform_state_bucket" {
  description = "S3 bucket used for Terraform remote state."
  value       = module.s3_backend.bucket_name
}

output "terraform_lock_table" {
  description = "DynamoDB table used for Terraform state locking."
  value       = module.s3_backend.table_name
}

output "vpc_id" {
  description = "ID of the project VPC."
  value       = module.vpc.vpc_id
}

output "public_subnet_ids" {
  description = "Public subnet IDs."
  value       = module.vpc.public_subnet_ids
}

output "private_subnet_ids" {
  description = "Private subnet IDs used by EKS nodes and RDS."
  value       = module.vpc.private_subnet_ids
}

output "ecr_repository_url" {
  description = "ECR repository URL used by Jenkins and the Django deployment."
  value       = module.ecr.repository_url
}

output "cluster_name" {
  description = "EKS cluster name."
  value       = module.eks.cluster_name
}

output "cluster_endpoint" {
  description = "EKS Kubernetes API endpoint."
  value       = module.eks.cluster_endpoint
  sensitive   = true
}

output "database_type" {
  description = "Created database type: RDS or Aurora."
  value       = module.rds.database_type
}

output "database_endpoint" {
  description = "Database connection endpoint."
  value       = module.rds.database_endpoint
}

output "database_port" {
  description = "Database connection port."
  value       = module.rds.database_port
}

output "database_password" {
  description = "Generated/explicit database password when Terraform manages it directly. Null when AWS Secrets Manager manages it."
  value       = module.rds.database_password
  sensitive   = true
}

output "jenkins_admin_username" {
  description = "Jenkins administrator username."
  value       = module.jenkins.admin_username
}

output "jenkins_admin_password" {
  description = "Jenkins administrator password generated by Terraform."
  value       = module.jenkins.admin_password
  sensitive   = true
}

output "grafana_admin_username" {
  description = "Grafana administrator username."
  value       = module.monitoring.grafana_admin_username
}

output "grafana_admin_password" {
  description = "Grafana administrator password generated by Terraform."
  value       = module.monitoring.grafana_admin_password
  sensitive   = true
}

output "jenkins_port_forward_command" {
  description = "Command used to access Jenkins locally."
  value       = "kubectl port-forward svc/jenkins 8080:8080 -n ${var.jenkins_namespace}"
}

output "argocd_port_forward_command" {
  description = "Command used to access Argo CD locally."
  value       = "kubectl port-forward svc/argocd-server 8081:443 -n ${var.argocd_namespace}"
}

output "grafana_port_forward_command" {
  description = "Command used to access Grafana locally."
  value       = "kubectl port-forward svc/grafana 3000:80 -n ${var.monitoring_namespace}"
}

output "prometheus_port_forward_command" {
  description = "Command used to access the Prometheus server locally."
  value       = "kubectl port-forward svc/prometheus-operated 9090:9090 -n ${var.monitoring_namespace}"
}

output "argocd_initial_password_command" {
  description = "Command that reads the initial Argo CD admin password from Kubernetes."
  value       = "kubectl -n ${var.argocd_namespace} get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 --decode"
}
